ER
dexias9024/vtuber_song_search pull request #3
Opened 2023-10-04 09:48 UTC by dexias9024

[![Image from Gyazo](https://i.gyazo.com/83505093156425af62cf428f816cbe0e.png)](https://gyazo.com/83505093156425af62cf428f816cbe0e)

Vtubersテーブル
Vtuberの基本情報と紐付けの情報を記録するテーブルです

Songsテーブル
歌の基本情報を紐付けを記録します。coverカラムはカバーの場合とオリジナルの場合を識別するために用意しました。nameとartist_nameは検索用です

Usersテーブル
ユーザーの情報を記録します。

membersテーブル
Vtuberの所属を表します。検索に使用します

instrumentsテーブル
Vtuberが弾ける楽器を記録します。複数弾ける場合を想定して関連テーブルVtuber _instrumentsを作りました。

commentsテーブル
歌のリンクに感想をユーザーがコメントするために用意しました。

user_favoritesテーブル
お気に入りのリストを作るためUsersとSongsの関連テーブルです。

user_requestsテーブル
ユーザーの登録してほしいVtuberと曲のリクエストを受けるためのテーブルです。request_typeでVtuberかSongかを識別します。所属と楽器はデータの取得が難しいのでユーザーからのリクエストで補完していくために用意しました。

inquerysテーブル
お問合せ内容を記録するテーブルです。

2023-10-05 03:12 UTC, Tsuchiya2 commented
ご提出ありがとうございます。
以下コメントになります。

---

■共通
・テーブル名は複数形に統一しましょう。
・テーブル名ですが、小文字・大文字から書かれていたりと統一性がないので統一してください。
・一部ではなく、各テーブル・各カラムの説明をコメント欄に記載してください。
・多対多のリレーションが散見されますが、正しいか確認して修正してください。

■usersテーブル
・password：こちらは何を使ってログイン機能を実装されようとしていますか。soceryだとすると、適切なカラムになっていないようなので確認して修正してください。

---

一旦上記の対応をお願いいたします。

2023-10-05 06:12 UTC, dexias9024 commented
文字とリレーションの見直しをしvtuber _instrumentsテーブルを削除しました。
[![Image from Gyazo](https://i.gyazo.com/6e68705c346742ceedc19d0bb9849b4e.png)](https://gyazo.com/6e68705c346742ceedc19d0bb9849b4e)

vtubersテーブル
Vtuberの基本情報を記録するテーブルです
チャンネル名、youtubeの概要欄、チャンネルのURL、アイコン、Vtuberの名前の基本情報と所属団体、弾ける楽器を関連付けしたID、作成時期と更新時期を記録します。検索と表示に使います。

songsテーブル
歌の基本情報を紐付けを記録します。タイトル、歌の名前、カバーかどうか、歌っているのは誰か、、動画のIDの基本情報を記録します。coverカラムはカバーの場合とオリジナルの場合を識別するために用意しました。nameとartist_nameは検索用です。
Vtuberテーブルと紐づいているのでarist_nameは必要ないように感じるかも知れませんがコラボで複数人で歌っているパターンがあるので個別に設定しています。

usersテーブル
ユーザーの情報を記録します。名前、パスワード、email、アイコン、プロフィール、作成時期、更新時期の基本情報を記録します。roleは自動取得のミスの修正などに管理者が必要なため用意しました。

membersテーブル
Vtuberの所属を表します。所属団体の名前は検索に使用します

instrumentsテーブル
Vtuberが弾ける楽器を記録します。楽器名は検索に使用します

commentsテーブル
歌のリンクに感想をユーザーがコメントするために用意しました。usersとsongテーブルの関連テーブルでcontentに動画へのコメントを記録します。

user_favoritesテーブル
お気に入りのリストを作るためUsersとSongsの関連テーブルです。

user_requestsテーブル
ユーザーの登録してほしいVtuberと曲のリクエストを受けるためのテーブルです。request_typeでVtuberかSongかを識別します。照合を行い登録するのでチャンネル名または歌動画の名前をnameに格納し、それぞれのURLをurlに保存します。所属と楽器はデータの取得が難しいのでユーザーからのリクエストで補完していくために用意しました。

inquerysテーブル
お問合せ内容を記録するテーブルです。nameとemailに問い合わせした人の情報を保存し、問い合わせ内容をcontentに格納し、作成された時と回答または解決した場合にclosed_atに時間を入れ表示しないようにするために用意しました。

2023-10-05 12:18 UTC, snrrrns requested changes
- ER図における矢印の使用方法が正しくないようです。以下の記事を参考に修正してください。

やさしい図解で学ぶ　ER図　表記法一覧
https://qiita.com/ramuneru/items/32fbf3032b625f71b69d

やさしい図解で学ぶ　中間テーブル　多対多　概念編
https://qiita.com/ramuneru/items/db43589551dd0c00fef9

- vtubersとmenbersを関連付ける矢印を、テーブル図に重ならない位置に配置し直してください。

2023-10-05 16:27 UTC, dexias9024 commented
修正しました。
多対多の関係を中間テーブルで表しているので中間テーブルに対して多対多になっていたのがおかしかったということでいいでしょうか？
[![Image from Gyazo](https://i.gyazo.com/d12616f223817c26c628a02703e41359.png)](https://gyazo.com/d12616f223817c26c628a02703e41359)

2023-10-06 06:30 UTC, kenchasonakai commented
> 多対多の関係を中間テーブルで表しているので中間テーブルに対して多対多になっていたのがおかしかったということでいいでしょうか？

その認識で大丈夫です

membersは所属団体を表すとのことですが、membersテーブルがvtubers_idを持っているのはなにか意図がありますか？

vtuberは一つの楽器しか演奏できない想定であってますでしょうか？
複数演奏可能なのであれば中間テーブルが必要そうです

user_requestsテーブルにrequest_typeを使っていますがRailsを使う想定であれば避けたほうが良さそうです
[typeを使わないほうがいい理由](https://railsguides.jp/active_record_basics.html#%E3%82%B9%E3%82%AD%E3%83%BC%E3%83%9E%E3%81%AE%E3%83%AB%E3%83%BC%E3%83%AB:~:text=%E3%81%93%E3%82%8C%E3%82%89%E3%81%AE%E3%82%AB%E3%83%A9%E3%83%A0%E5%90%8D%E3%81%AF%E5%BF%85%E9%A0%88%E3%81%A7%E3%81%AF%E3%81%82%E3%82%8A%E3%81%BE%E3%81%9B%E3%82%93%E3%81%8C%E3%80%81Active%20Record%E3%81%A7%E4%BA%88%E7%B4%84%E3%81%95%E3%82%8C%E3%81%A6%E3%81%84%E3%81%BE%E3%81%99%E3%80%82%E7%89%B9%E5%88%A5%E3%81%AA%E7%90%86%E7%94%B1%E3%81%AE%E3%81%AA%E3%81%84%E9%99%90%E3%82%8A%E3%80%81%E3%81%93%E3%82%8C%E3%82%89%E3%81%AE%E4%BA%88%E7%B4%84%E6%B8%88%E3%81%BF%E3%82%AB%E3%83%A9%E3%83%A0%E5%90%8D%E3%81%A8%E5%90%8C%E3%81%98%E3%82%AB%E3%83%A9%E3%83%A0%E5%90%8D%E3%81%AE%E5%88%A9%E7%94%A8%E3%81%AF%E9%81%BF%E3%81%91%E3%81%A6%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84%E3%80%82%E3%81%9F%E3%81%A8%E3%81%88%E3%81%B0%E3%80%81type%E3%81%A8%E3%81%84%E3%81%86%E8%AA%9E%E3%81%AF%E3%83%86%E3%83%BC%E3%83%96%E3%83%AB%E3%81%A7STI%EF%BC%88Single%20Table%20Inheritance%EF%BC%89%E3%82%92%E6%8C%87%E5%AE%9A%E3%81%99%E3%82%8B%E3%81%9F%E3%82%81%E3%81%AB%E4%BA%88%E7%B4%84%E3%81%95%E3%82%8C%E3%81%A6%E3%81%84%E3%81%BE%E3%81%99%E3%80%82STI%E3%82%92%E4%BD%BF%E3%82%8F%E3%81%AA%E3%81%84%E5%A0%B4%E5%90%88%E3%81%A7%E3%81%82%E3%81%A3%E3%81%A6%E3%82%82%E3%80%81%E4%BA%88%E7%B4%84%E8%AA%9E%E3%82%88%E3%82%8A%E5%85%88%E3%81%AB%E3%81%BE%E3%81%9A%E3%80%8Ccontext%E3%80%8D%E3%81%AA%E3%81%A9%E3%81%AE%E3%82%88%E3%81%86%E3%81%AA%E3%83%A2%E3%83%87%E3%83%AB%E3%81%AE%E3%83%87%E3%83%BC%E3%82%BF%E3%82%92%E9%81%A9%E5%88%87%E3%81%AB%E8%A1%A8%E3%81%99%E8%AA%9E%E3%82%92%E6%A4%9C%E8%A8%8E%E3%81%97%E3%81%A6%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84%E3%80%82)

2023-10-06 06:58 UTC, dexias9024 commented
修正しました。
membersテーブルのvtubers_idは必要なさそうなので削除しました。
楽器は複数演奏可能な人もいるので中間テーブルのvtuber_instrumentsテーブルを作成しました。
カラムは関連付けるidのみです
user_requestsテーブルのrequest_typeはrequest_statusに変更しました。
[![Image from Gyazo](https://i.gyazo.com/f996d7a9a4d50e95ff11c6685066af5a.png)](https://gyazo.com/f996d7a9a4d50e95ff11c6685066af5a)

2023-10-06 10:52 UTC, tarakish requested changes
修正良いと思います👍
追加で一点コメントです。

---

user_requestsのinstruments_nameについて
こちらリクエストで入力させるのは良いと思いますが、登録の自動化はどのようなフローで考えていますでしょうか？
完全な自動化、となるとユーザーの入力値から楽器を登録することとなりますが、表記揺れにより同じ楽器でも別の名前で登録されることが相次ぐと検索機能が機能しなくなりそうです。
もし楽器数がそれほど多くないのであれば、stringでの入力ではなくinstrrumentsからマルチセレクトボックスなどで実装したほうがよいかもしれません。
その場合はuser_requestsとinstrumentsを多対多で紐付けるイメージですね。

上記一度ご確認をお願いします！

2023-10-06 12:15 UTC, dexias9024 commented
確かに表記揺れの問題は起きそうです
なのでuser_requestからinstruments_nameを削除しました
seedでinstrumentsテーブルに楽器名を入れるようにしようと思います
[![Image from Gyazo](https://i.gyazo.com/4d1ac60db383638dd7604c0089a239e8.png)](https://gyazo.com/4d1ac60db383638dd7604c0089a239e8)

2023-10-06 12:19 UTC, tarakish reviewed
> 確かに表記揺れの問題は起きそうです
なのでuser_requestからinstruments_nameを削除しました
seedでinstrumentsテーブルに楽器名を入れるようにしようと思います

良いと思います。
添付されたスクリーンショットでは、user_requestsとinstrumentsに関連がなく、このままではuser_requestsの楽器についてのデータを保持できないのでテーブルを追加する必要がありますね

2023-10-06 13:26 UTC, dexias9024 commented
修正したのですがuser_requestsとinstrumentsテーブルの関連付けをコピーした内容をVtuberテーブルとinstrumentsテーブルの関連テーブルに保存することは可能なのでしょうか？
[![Image from Gyazo](https://i.gyazo.com/859d8846c1f32ae0f2fbb5aabcb13505.png)](https://gyazo.com/859d8846c1f32ae0f2fbb5aabcb13505)

2023-10-07 02:21 UTC, Tsuchiya2 commented
概ね良さそうかと思います。LGTMです。

2023-10-07 05:30 UTC, dexias9024 commented
ありがとうございます！

2023-10-07 05:45 UTC, merged